#+TITLE:       Teach Yourself Scheme in Fixnum Days
#+AUTHOR:      Yali Bian
#+EMAIL:       byl.lisp@gmail.com
#+DATE:        2015-07-20 Mon


* Enter Scheme
* Data types

  A data type is a collection of related values. These collections need not to be disjoint, and they are often hierarchical. Scheme has a rich set of data types: some are simple (indivisible) data types and others are compound data types made by combining other data types.

** Simple data types

   The simple data types of Scheme include booleans, numbers, characters, and symbols.

*** Booleans

    Scheme's booleans are #t for true and #f for false.

    The procedure not negates its argument, considered as a boolean.

    In a context that requires a boolean, Scheme will treat any value that is not #f as a true value.

#+BEGIN_SRC racket

(not "Hello, World!") ; => #f

#+END_SRC

*** Numbers

    Scheme numbers can be integers (eg, 42), rationals (22/7), reals (3.1416), or complex (2+2i). An integer is a rational is a real is a complex number is a number.

    Scheme integers need not be specified in decimal (base 10) format. They can be specified in binary by prefixing the numeral with #b. Thus #b1100 is the number twelve. The octal prefix is #o and the hex prefix is #x. (The optional decimal prefix is #d.)

    Numbers can tested for equality using the general-purpose equality predict eqv?

*** Characters

    Scheme character data are represented by prefixing the character with #\. Thus #\c is the character c.

**** Non-graphic characters

    Some non-graphic characters have more descriptive names, eg, #\newline, #\tab. The character for space can be written #\ , or more readably, #\space.

    #+BEGIN_SRC racket
    (char? #\;)
    #+END_SRC

    Note that a semicolon character datum does not trigger a comment.

*** Symbols

    The simple data types we saw above are self-evaluating. Ie, if you typed any object from these data types to the listener, the evaluated result returned by the listener will be the same as what you typed in.

    #+BEGIN_SRC racket
    #t
    42
    #\c
    #+END_SRC

    Symbols do not behave the same way. This is because symbols are used by Scheme programs as identifiers for variables, and thus will evaluate to the value that the variable holds. Nevertheless, symbols are a simple data type, and symbols are legitimate values that Scheme can traffic in, along with characters,numbers, and the rest.

    To specify a symbol without making Scheme think it is a a variable, you should quote the symbol:

    #+BEGIN_SRC racket

    (quote xyz)

    #+END_SRC

    Since this type of quoting is very common in Scheme, a convenient abbreviation is provided. The expression
    #+BEGIN_SRC racket
    'E
    #+END_SRC

    Scheme symbols are named by a sequence of characters. About the only limitation on a symbol's name is that it shouldn't be mistakable for some other data, eg, characters or booleans or numbers or compound data.

    Scheme symbols are normally case-insensitive. Thus the symbols Calorie and calorie are identical:

    #+BEGIN_SRC racket
    (define x 9)
    (symbol? x)
    #+END_SRC

** Compound data types

   Compound data types are built by combining values from other data types in structured ways.

*** Strings

    Strings are sequences of characters (not to be confused with symbols, which are simple data that _have a sequence of characters as their name_). You can specify strings by enclosing the constituent characters in double-quotes.

*** Vector

    Vectors are sequences like strings, but their elements can be anything, not just characters. Indeed, the elements can be vectors themselves, which is a good way to generate multidimensional vectors.

*** Dotted pairs and lists

    A dotted pair is a compound value made my combining any two arbitrary values into an *ordered couple*. The first element is called the car, the second element is called the cdr, and the combining procedure is cons.

    Dotted pairs are not *self-evaluating*, and so to specify them directory as data (ie, without producing them via a cons-call), one must explicitly quote them:

    '(1 . #t)

    Scheme provides a further abbreviation if the last cdr is a special object called the empty list, which is represented by the expression (). The empty list is not considered self-evaluating, and so one should quote it when supply it as a value in a program.

    This special kind of nested dotted pair is called a list.

*** Conversions between data types

    Characters can be converted into integers using char->integer, and integers can be converted into characters using integer->char.
    The integer corresponding to a character is usually its ascii code.

** Other data types

   Scheme contains some other data types. One is the procedure.

   The procedures we have seen thus far are primitive procedures, with standard global variables holding them.

   Yet another data type is the port. A port is the conduit through which input and output is performed. Ports are usually associated with files and consoles.


** S-expression

   All the data types discussed here can be lumped together into a single all-encompassing data type called the s-expression (s for symbolic). Thus 43, #\c, (1 . 2), #(a b c), "hello", (quote xyz), (string-number "16"), and (begin (display "hello, world!")(newline)) are all s-expression.

* Forms

  The reader will have note that the Scheme example programs provided thus far are also s-expression. This is true of all Scheme programs: Programs are data.

  Thus, the character datum #\c is a program, or a form. We will use the more general term form instead of program, so that we can deal with program fragments too.

  Scheme evaluates the form #\c to the value #\c, because #\c is self-evaluating. Not all s-expressions are self-evaluating. For instance the symbol s-expression /xyz/ evaluates to the value held by the variable /xyz/. The list s-expression (string->number "16") evaluates to the number 16.

  Not all s-expressions are valid programs. If you typed the dotted-pair s-expression (1 . 2), at the Scheme listener, you will get an error.

  Scheme evaluates a list form by examining the first element, or head, of the form. If the head evaluates to a procedure, the rest of the form is evaluated to get the procedure's arguments, and the procedure is applied to the arguments.

  If the head of the form is a *special form*, the evaluation proceeds in a manner idiosyncratic to that form. Some special forms we have already seen are begin, define, and set!. begin causes its subforms to be evaluated in order, the result of the entire form being the result of the last subform. define introduces and initializes a variable. set! changes the binding of a variable.

** Procedures

   We used the *begin* special form to bunch together a group of subforms that need to be evaluated in sequence. (在平常的 procedure 里面，所有的参数，都是无序的进行 evaluate 的， 要想进行将所有的参数，务必进行由左到右的 evaluate，我们则需要使用 special form *begin*.)

   #+BEGIN_SRC racket

(define display-seq (lambda (arg1 arg2 arg3)
                   (begin
                     [display arg1]
                     [display " "]
                     [display arg2]
                     [display " "]
                     [display arg3]
                     [newline])))

   #+END_SRC

   In Scheme, lambda-bodies are implicit beginS. Thus, the begin in display3's body isn't needed, although it doesn't hurt. display3, more simply, is:

   #+BEGIN_SRC racket

(define display-seq (lambda (arg1 arg2 arg3)
                     [display arg1]
                     [display " "]
                     [display arg2]
                     [display " "]
                     [display arg3]
                     [newline]))

   #+END_SRC

* Conditionals

  Like all languages, Scheme provides conditionals.

** when and unless

** Cond

   The cond is a multi-branch conditional.


* Lexical variables
* Recursion

** letrec
** Named let

   Scheme allows a variant of let called named let to write this kind of loop more compactly:

** Iteration

#+BEGIN_SRC Scheme

(let countdown ((i 0))
   (if (= i 0) 'liftoff
       (begin
          (display i)
          (newline)
          (countdown (- i 1)))))

#+END_SRC

   /countdown/ defined above is really a recursive procedure. Scheme can define loops only through recursion. There are no special looping or iteration constructs.

   Nevertheless, the loop as defined above is a genuine loop, in exactly the same way that other language bill their loops. Ie, Scheme takes special care to ensure that recursion of the type used above will not generate the procedure call/return overhead.

   Scheme does this by a process called tail-call elimination. If you look closely at the countdown procedure, you will note that when the recursive call occurs in countdown's body, it is the tail call, or the very last thing done - each invocation of /countdown/ either does not call itself, or when it does, it does so as its very last act. To a Scheme implementation, this makes the recursion indistinguishable from iteration. So go ahead, use recursion to write loops. It's safe.

   Here's another example of a useful tail-recursive procedure:

   #+BEGIN_SRC Scheme

   (define list-position (lambda (o l)
                             (let loop ((i 0) (l l))
                                (if (null? l) #f
                                    (if (eqv? (car l) o) i
                                        (loop (+ i 1) (cdr l)))))))

   #+END_SRC

   /list-position/ finds the index of the first occurrence of the object /o/ i the list /l/. If the object is not found in the list, the procedure returns #f.

   Here's yet another tail-recursive procedure, one that reverses its argument list "in place", ie., by mutating the contents of the existing list, and without allocating a new one:

   #+BEGIN_SRC Scheme

   (define reverse! (lambda (s)
                        (let loop ((s s) (r '()))
                          (if (null? s) r
                              (let ((d (cdr s)))
                                   (set-cdr! s r)
                                   (loop d s))))))

   #+END_SRC

   (/reverse!/ is a useful enough procedure that it is provided primitively in many Scheme dialects, eg, MzScheme and Guile.)
** Mapping a procedure across a list
* I/O

  Scheme has input/output (I/O) procedures that will let you read from an input port or write to an output port. Ports can be associated with console, files or strings.

** Reading

   Scheme's reader procedures take an optional input port argument. If the port is not specified, the current input port port (usually the console) is assumed.

   Reading can be character-, line- or s-expression-based. Each time a read is performed. the port's state changed so that the next read will read material following what was already read. If the port has no more material to be read, the reader procedure returns a specific datum called the end-of-file or eof object.

** Writing

   The procedure write and display both write the given s-expression to the port, with one different: write attempts to use a machine-readable format and display doesn't. Eg, write uses double quotes for strings and the #\ syntax for characters. displays doesn't.

   The procedure newline starts a new line on the output port.

** File ports

   Scheme's I/O procedures do not need a port argument if the port happens to be standard input or standard output. However, if you need these ports explicitly, the zero-argument procedures current-input-port and current-output-port furnish them. Thus,

   #+BEGIN_SRC Scheme

   (display 9)
   (display 9 (current-output-port))

   #+END_SRC

   have the same behavior.

** String ports
** Loading files

   Loading a file consists in evaluating in sequence every Scheme form in the file. The pathname argument given to /load/ is reckoned relative to the current working directory of Scheme, which is normally the directory in which the Scheme executable was called.

* Macros

  Users can create their own special forms by defining /macros/. A macro is a symbol that has a transformer procedure associated with it.  When Scheme encounters a macro-expression - ie, a form whose head is a macro-, it applies the macro's transformer to the subforms in the macro-expression, and evaluates the result of the transformation.

  Ideally, a macro specifies a purely textual transformation from code text to other code text. This kind of transformation is useful for abbreviating an involved and perhaps frequently occurring *textual pattern*.

  A macro is defined using the special form define-macro. For example, if your Scheme lacks the conditional special form /when/, you could define /when/ as the following macro:

  #+BEGIN_SRC Scheme

  (define-macro when
     (lambda (test . branch)
       (list 'if test
         (cons 'begin branch))))

  #+END_SRC

  This defines a when-transformer that would convert a when-expression into equivalent if-expression. With this macro definition in place, the when-expression:

  #+BEGIN_SRC Scheme

  (when (< (pressure tube) 60)
    (open-value tube)
    (attach floor-pump tube)
    (depress floor-pump 5)
    (detach floor-pump tube)
    (close-valve tube))

  #+END_SRC

  will be converted to another expression, the result of applying the when-transformer to the when-expression's subforms:

  #+BEGIN_SRC Scheme

  (apply (lambda (test . branch)
           (list 'if test (cons 'begin branch)))
         '((< (pressure tube) 60)
           (open-value tube)
           (attach floor-pump tube)
           (depress floor-pump 5)
           (detach floor-pump tube)
           (close-valve tube))))

  #+END_SRC

  The transformation yields the list:

  #+BEGIN_SRC Scheme

   (if (< (pressure tube) 60)
       (begin
         (open-value tube)
         (attach floor-pump tube)
         (depress floor-pump 5)
         (detach floor-pump tube)
         (close-valve tube)))

  #+END_SRC

  Scheme will then evaluate this expression, as it would any other.

** Specifying the expansion as a template

   A macro transformer takes some s-expressions and produces an s-expression that will be used as a form. Typically this output is a list. In our /when/ example, the output list is created using

   #+BEGIN_SRC Scheme

   (list 'if test
     (cons 'begin branch))

   #+END_SRC

   Output lists can be quite complicated. It is easy to see that a more ambitious macro than /when/ could lead to quite an elaborate construction process for the output list. In such cases, it is more convenient to specify the macro's output form as a template, with the macro arguments inserted at appropriate places to fill out the template for each particular use of the macro. Scheme provides the backquote syntax to specify such templates. Thus the expression

   #+BEGIN_SRC Scheme
   (list 'IF test
     (cons 'BEGIN branch))
   #+END_SRC

   is more conveniently written as

   #+BEGIN_SRC Scheme
   `(IF ,test
      (BEGIN ,@branch))
   #+END_SRC

   We can refashion the /when/ macro-definition as:

   #+BEGIN_SRC Scheme

   (define-macro when
     (lambda ((test . branch)
       `(IF ,test
            (BEGIN ,@branch)))))

   #+END_SRC

   Note that the template format, unlike the earlier list construction, gives immediate visual indication of the shape of the output list. The backquote (`) introduces a template for a list. The elements of the template appear /verbatim/ in the resulting list, except when they are prefixed by a comma (',') or a comma-splice (',@'). (For the purpose of illustration, we have written the verbatim elements of the template in UPPER_CASE)

   The comma and the comma-splice are used to insert the macro arguments into the template. The comma inserts the result of evaluating its following expression. The comma-splice inserts the result of evaluating its following expression after splicing it, ie, it removes the outermost set of parentheses. (This implies that an expression introduced by comma-splice must be a list.)

** Avoid variable capture inside macros
*** store if-test result in a local variable
*** choose local variables inside macro definitions
*** generated symbols

    A more reliable, if verbose, approach is to use generated symbols that are guaranteed not to be obtainable by other means. The procedure gensym generates unique symbols each time it is called.

** fluid-let
* Structures

  The fields could be accessed using vector-ref and modified using vector-set!. Nevertheless, we wouldn't want to be saddled with the burden of remembering which vector index corresponds to which field. That would be a thankless and error-prone activity, especially if fields get excluded or included over the course of time. We will therefore use a Scheme Macro /defstruct/ to define a structure data type, which is basically a vector, but which comes with an appropriate suite of procedures for creating instances of the structure, and for accessing and modifying its fields.

* Alists and tables
* System interface

  Useful Scheme programs often need to interact with the underlying operating system.

** Checking for and deleting files
** Calling operating-system commands
** Environment variables
* Objects and classes
* Jumps

  One of the signal features of Scheme is its support for jumps or nonlocal control. Specifically, Scheme allows program control to jump arbitrary locations in the program, in contrast to the more restrained forms of program control flow allowed by *conditionals and procedure calls*. Scheme's nonlocal control operators is a procedure named call-with-current-continuation. We will see how this operator can be used to create a breathtaking variety of *control idioms*.

** call-with-current-continuation

   The operator call-with-current-continuation /calls/ its argument, which must be a unary procedure, with a value called the "current continuation". If nothing else, this explains the name of the operator. But it is a long name, and is often abbreviated call/cc.

   The current continuation at any point in the execution of a program is an abstraction of the rest of the program. Thus in the program

   #+BEGIN_SRC Scheme

   (+ 1 (call/cc (lambda (k)
                   (+ 2 (k 3)))))

   #+END_SRC

   the rest of the program, from the point of view of the call/cc-application, is the following program-with-a-hole (with [] representing the hole):

   #+BEGIN_SRC Scheme

   (+ 1 [])

   #+END_SRC

   In other words, this continuation is a program that will add 1 to whatever is used to fill its hole.

   This is what the argument of call/cc is called with. Remember that the argument of call/cc is the procedure

   #+BEGIN_SRC Scheme

   (lambda (k)
     (+ 2 (k 3)))

   #+END_SRC

   This procedure's body applies the continuation (bound now to the parameter k) to the argument 3. This is when the unusual aspect of the continuation springs to the fore.

   The continuation call abruptly abandons its own computation and replaces it with the rest of the program saved in k! In other words, the part of the procedure involving the addition of 2 is jettisoned, and k's argument 3 is sent directly to the program-with-the-hole:

   #+BEGIN_SRC Scheme
   (+ 1 [])
   #+END_SRC

   The program now running is simply

   #+BEGIN_SRC Scheme

   (+ 1 3)

   #+END_SRC

   which returns 4. In sum,

   #+BEGIN_SRC Scheme
   (+ 1 (call/cc (lambda (k)
                   (+ 2 (k 3)))))
   #+END_SRC

   The above illustrates that what is called an escaping continuation, one used to exit out of a computation (here: the (+ 2 []) computation). This is useful property, but Scheme's continuations can also be used to return to previously abandoned contexts, and indeed to invoke them many times. The "rest of the program" ("the rest of the program" 的真正的含义，哪里是rest program的开始，哪里是program 的结束。) enshrined in a continuation is available whenever and how many ever times we choose to recall it, and this is what contributes to the great and sometimes confusing versatility of call/cc. As a quick example, type the following at the listener:

   #+BEGIN_SRC Scheme

   (define r #f)

   (+ 1 (call/cc (lambda (k)
                   (set! r k)
                   (+ 2 (k 3)))))

   #+END_SRC

   The latter expression returns 4 as before. The difference between this use of call/cc and the previous example is that here we also store the continuation k in a global variable r.

   Now we have a permanent record of the continuation in r. If we call it on a number, it will return that number incremented by 1:

   #+BEGIN_SRC Scheme
   (r 5)
   ; ==> 6
   #+END_SRC

   Not that r will abandon its own continuation, which is better illustrated by embedding the call to r inside some context:

   #+BEGIN_SRC Scheme

   (+ 3 (r 5))

   #+END_SRC

   The continuations provided by call/cc are thus abortive continuations.

   但是我在begin中使用continuation的时候，就不会abortive后面的内容：

   #+BEGIN_SRC Scheme

   (begin (r 6)
     (display "Hello World!"))
   ; display will be evaluated
   ; "Hello, World!" will be printed.

   #+END_SRC

所以，对于程序执行过程中，每个 continuation 的创建，在它创建后，他的子 continuation 的创建，而不是一个新的continuation 对它的覆盖，这个整个机制，我需要理解开来。 或者是begin syntax 这个 special form的理解？？？！！！！

** Escaping continuations

   Escaping continuations are the simplest use of call/cc and are very useful for programming procedure or loop exits. Consider a procedure list-product that takes a list of numbers and multiplies them. A straightforward recursive definition for list-product is:

   #+BEGIN_SRC Scheme

   (define list-product (lambda (s)
                          (let recur ((s s))
                            (if (null? s) 1
                                (* (car s) (recur (cdr s)))))))

   #+END_SRC

   This is a problem with this solution. If one of the elements in this list is 0, and if there are many elements after 0 in the list, then the answer is foregone conclusion. Yet, the code will have us to through many fruitless recursive calls to recur before producing the answer. This is where an escape continuation comes in handy. Using call/cc, we can rewrite the procedure as:

   #+BEGIN_SRC Scheme

   (define list-product (lambda (s)
                          (call/cc
                            (lambda (exit)
                              (let recur ((s s))
                                    (if (null? s) 1
                                        (if (= (car s) 0) (exit 0)
                                            (* (car s) (recur (cdr s))))))))))

   #+END_SRC

   If a 0 element is encountered, the continuation /exit/ is called with 0, thereby avoiding further calls to recur.

** Tree matching

   A more involved example of continuation usage is the problem of determining if two trees (arbitrarily nested dotted pairs) have the same fringe, ie., the same elements (or leaves) in the same sequence. Eg,

   #+BEGIN_SRC Scheme

   (same-fringe? '(1 (2 3) '((1 2) 3)))
   ; -> #t

   (same-fringe? '(1 2 3) '(1 (3 2)))
   ; -> #f

   #+END_SRC

   The purely functional approach is to flatten both trees and check if the results match.

   #+BEGIN_SRC Scheme

(define same-fringe? (lambda (tree1 tree2)
                       (let loop ((ftree1 (flatten tree1))
                                  (ftree2 (flatten tree2)))
                         (cond
                           [(and (null? ftree1) (null? ftree2)) #t]
                           [(or (null? ftree1) (null? ftree2)) #f]
                           [(eqv? (car ftree1) (car ftree2)) (loop (cdr ftree1) (cdr ftree2))]
                           [else #f]
                           ))))

(define flatten (lambda (tree)
                    (cond
                      [(null? tree) '()]
                      [(pair? (car tree)) (append (flatten (car tree))
                                                  (flatten (cdr tree)))]
                      [else (cons (car tree)
                                  (flatten (cdr tree)))])))

   #+END_SRC

   However, this traverses the trees completely to flatten them, and then again till it finds non-matching elements. Furthermore, even the best flattening algorithms will require consES equal to the total number of leaves. (Destructively modifying the input trees is not an option.)

   We can use call/cc to solve the problem without needless traversal and without any consING. Each tree is mapped to a generator, a procedure with internal state that successively produces the leaves of the tree in left-to-right order that they occur in the tree.

   #+BEGIN_SRC Scheme

; tree->generator
(define tree->generator (lambda (tree)
                          (let ((caller '*))
                            (letrec ((generate-leaves (lambda ()
                                                        (let loop ((tree tree))
                                                          (cond
                                                            [(null? tree) 'skip]
                                                            [(pair? tree)
                                                             (loop (car tree))
                                                             (loop (cdr tree))]
                                                            [else (call/cc (lambda (rest-of-tree)
                                                                             (set! generate-leaves (lambda ()
                                                                                                     (rest-of-tree 'resume)))
                                                                             (caller tree)))]))
                                                        (caller '()))))
                              (lambda () (call/cc (lambda (k)
                                                    (set! caller k)
                                                    (generate-leaves))))))))

   #+END_SRC

   When a generator created by tree->generator is called, it will store the continuation of its call in caller, so that it can know who to send the leaf to when it finds it. It then calls an internal procedure called /generate-leaves/ which runs a loop traversing the tree from left to right. When the loop encounters a leaf, it will use caller to return the leaf as the generator's result, but it will remember to store the rest of the loop (captured as a call/cc continuation) in the /generate-leaves/ variable. The next time the generator is called, the loop is resumed where it left off so it can hunt for the next leaf.

   Note that the last thing /generate-leaves/ does, after the loop is done, is to return the empty list to the caller. Since the empty list it not a valid leaf value, we can use it to tell that the generator has no more leaves to generate.

   The procedure same-fringes? maps each of its tree arguments to a generator, and then calls these two generators alternatively. It announces failure as soon as two non-matching leaves are found:

   #+BEGIN_SRC Scheme

(define same-fringe?-2 (lambda (tree1 tree2)
                       (let ((gen1 (tree->generator tree1))
                             (gen2 (tree->generator tree2)))
                         (let loop ()
                           (let ((leaf1 (gen1))
                                 (leaf2 (gen2)))
                             (if (eqv? leaf1 leaf2) (if (null? leaf1) #t (loop))
                                 #f))))))

   #+END_SRC

** Coroutines

   The generators used above are interesting generalizations of the procedure concept. Each time the generator is called, it resumes its computation, and when it has a result for its caller returns it, but only after storing its continuation in an internal variable, so the generator can be resumed again. We can generalize generators further, so that they can mutually resume each other, sending results back and forth among themselves. Such procedures are called coroutines.

* Nondeterminism

  MaCarthy's nondeterministic operator *amb* is as old as Lisp itself, altough it is present in no Lisp. *amb* takes zero or more expressions, and makes a nondeterministic (or "ambiguous") choice among them, preferring those choices that cause the program to converge meaningfully. Here we will explore an embedding of *amb* in Scheme that makes a depth-first selection of the ambiguous choices, and uses Scheme's control operator call/cc to backtrack for alternate choices. The result is an elegant backtracking strategy that can be used for searching problem spaces directly in Scheme without recourse to an extended language.
* Engines

  An engine represents computation that is subject to timed preemption. In other words, an engine's underlying computation is an ordinary thunk that runs as a time-preemptable process.

  An engine is called with three arguments:

    - a number of time units or ticks
    - a success procedure
    - a failure procedure

  If the engine computation finishes within the allotted ticks, the success procedure is applied to the computation result and the remaining ticks. If the engine computation could not finish within the allotted ticks, the failure procedure is applied to a new engine representing the unfinished portion of the engine computation.

* Shell scripts

  It is often convenient to simply write what one wants done into a file or script, and execute the script as though it were any other operating-system shell command. The interface to more weighty programs is often provided in the form of a script, and users frequently build their own scripts or customize existing ones to suit particular needs. Scripting is arguably the most frequent programming task performed. For many users, it is the only programming they will ever do.

* CGI script
